"""empty message

Revision ID: f5978620b111
Revises: 20fa15861ab3
Create Date: 2019-10-10 17:04:15.222530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5978620b111'
down_revision = '20fa15861ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'state', ['state_id'], ['id'])
    op.create_foreign_key(None, 'artist', 'city', ['city_id'], ['id'])
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    op.add_column('venue', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venue', 'address', ['address_id'], ['id'])
    op.create_foreign_key(None, 'venue', 'state', ['state_id'], ['id'])
    op.create_foreign_key(None, 'venue', 'city', ['city_id'], ['id'])
    op.drop_column('venue', 'state')
    op.drop_column('venue', 'city')
    op.drop_column('venue', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'state_id')
    op.drop_column('venue', 'city_id')
    op.drop_column('venue', 'address_id')
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'state_id')
    op.drop_column('artist', 'city_id')
    op.drop_table('state')
    op.drop_table('city')
    op.drop_table('address')
    # ### end Alembic commands ###
